name: dadjokes
version: 1.3.0
description: A collection of terrible jokes.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  share: ^0.6.3+6
  auto_size_text: ^2.1.0
  google_fonts: ^0.3.10

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 888f58887b388f5e875662e1def33f2d12696564

dev_dependencies:
  pedantic: ^1.9.0
flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
   - assets/title-image.png

# On changing the icons below, run:
#   flutter packages run flutter_launcher_icons:main
# to update the various Android and iOS assets
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/source-icon.png"
  adaptive_icon_background: "assets/source-background.png"
  adaptive_icon_foreground: "assets/source-foreground.png"