name: dadjokes
version: 1.3.0
description: A collection of terrible jokes.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  share: ^0.6.3+3
  auto_size_text: ^2.1.0
  google_fonts: ^0.0.7

  window_size:
    path: plugins/window_size


dev_dependencies:
  pedantic: ^1.8.0+1
flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
   - assets/title-image.png
  fonts:
    - family: Patrick Hand
      fonts:
       - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500

# On changing the icons below, run:
#   flutter packages run flutter_launcher_icons:main
# to update the various Android and iOS assets
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/source-icon.png"
  adaptive_icon_background: "assets/source-background.png"
  adaptive_icon_foreground: "assets/source-foreground.png"