name: dadjokes
version: 1.2.0
description: A collection of terrible jokes.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  share: ^0.6.1+1
  auto_size_text: ^2.0.1

dev_dependencies:
  pedantic: 1.7.0
  flutter_launcher_icons: ^0.7.2

flutter:
  uses-material-design: true
  assets:
   - assets/icon.png
  fonts:
    - family: Patrick Hand
      fonts:
       - asset: assets/fonts/PatrickHand-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/source-icon.png"
  adaptive_icon_background: "assets/source-background.png"
  adaptive_icon_foreground: "assets/source-foreground.png"